default: &default
  adapter: mysql2
  encoding: utf8
  host: <%= SettingConfig.mysql.host %>
  reconnect: false
  database: <%= SettingConfig.mysql.database %>
  pool: 5
  username: <%= SettingConfig.mysql.username %>
  password: <%= SettingConfig.mysql.password %>
  
development:
  <<: *default

test:
  <<: *default


production:
  <<: *default
